[package]
name = "mcz"
version = "0.1.0"
edition = "2021"

[features]
tray = ["dep:ksni"]

[dependencies]
tokio = { version = "1", features = ["full"] }
rodio = { version = "0.19", default-features = false, features = ["symphonia-all"] }
zbus = { version = "4.4", default-features = false, features = ["tokio"] }
ksni = { version = "0.3", default-features = false, features = ["tokio"], optional = true }
log = "0.4"
